"""
Unified API routes — single file defining all endpoints.
All routes are prefixed with /api/v1 via the main router.
"""

import logging

from fastapi import APIRouter, File, Form, HTTPException, UploadFile
from fastapi.responses import StreamingResponse

from app.models.schemas import (
    AudioRequest,
    HealthResponse,
    NewsRequest,
    NewsResponse,
    SummarizeRequest,
    SummarizeResponse,
    TelegramStatusResponse,
)
from app.services.audio_service import generate_audio_stream
from app.services.llm_service import run_agent, summarize_news
from app.services.news_service import fetch_news
from app.services.telegram_service import get_connection, send_audio_to_user

logger = logging.getLogger(__name__)

router = APIRouter()


# ── Health ───────────────────────────────────────────────────────

@router.get(
    "/health",
    response_model=HealthResponse,
    tags=["Health"],
    summary="Service health check",
)
async def health_check():
    return HealthResponse(status="ok", version="1.0.0")


# ── News ─────────────────────────────────────────────────────────

@router.post(
    "/news/generate",
    response_model=NewsResponse,
    tags=["News"],
    summary="Generate AI-researched news summary for a topic",
)
async def generate_news(data: NewsRequest):
    """
    Uses a LangChain ReAct agent to search the web and produce
    a bullet-point summary of the latest news for the given topic.
    """
    try:
        result = run_agent(topic=data.topic)
        return NewsResponse(success=True, news=result)
    except ValueError as ve:
        raise HTTPException(status_code=422, detail=str(ve))
    except Exception as e:
        logger.error("POST /news/generate error: %s", e)
        raise HTTPException(status_code=500, detail=f"News generation failed: {e}")


@router.post(
    "/news/summarize",
    response_model=SummarizeResponse,
    tags=["News"],
    summary="Fetch articles and return a broadcast-style summary",
)
async def summarize_news_endpoint(data: SummarizeRequest):
    """
    Fetches fresh articles from RapidAPI and returns a broadcast-style
    news summary generated by the xAI Grok LLM.
    """
    try:
        news_data = fetch_news(
            query=data.topic,
            limit=data.limit,
            time_published=data.time_published,
        )
        articles = news_data.get("data", []) if news_data else []

        summary = summarize_news(topic=data.topic, articles=articles)

        return SummarizeResponse(
            success=True,
            topic=data.topic,
            article_count=len(articles),
            summary=summary,
        )
    except ValueError as ve:
        raise HTTPException(status_code=422, detail=str(ve))
    except Exception as e:
        logger.error("POST /news/summarize error: %s", e)
        raise HTTPException(status_code=500, detail=f"Summary generation failed: {e}")


# ── Audio ────────────────────────────────────────────────────────

@router.post(
    "/audio/news",
    tags=["Audio"],
    summary="Full pipeline: fetch → summarize → TTS → stream MP3",
)
async def news_audio_endpoint(data: AudioRequest):
    """
    End-to-end pipeline in one call:
      1. Fetch fresh articles via RapidAPI
      2. Summarize with xAI Grok LLM (broadcast-style script)
      3. Convert the script to speech via gTTS
      4. Stream MP3 bytes directly back to the client
    """
    # Step 1 — Fetch articles
    try:
        news_data = fetch_news(
            query=data.topic,
            limit=data.limit,
            time_published=data.time_published,
        )
        articles = news_data.get("data", []) if news_data else []
    except Exception as e:
        logger.error("POST /audio/news fetch error: %s", e)
        raise HTTPException(status_code=502, detail=f"News fetch failed: {e}")

    # Step 2 — Summarize
    try:
        script = summarize_news(topic=data.topic, articles=articles)
    except Exception as e:
        logger.error("POST /audio/news summarize error: %s", e)
        raise HTTPException(status_code=500, detail=f"Summary generation failed: {e}")

    # Step 3+4 — TTS → Stream
    try:
        audio_stream = generate_audio_stream(
            script=script,
            voice_id=data.voice_id,
            model_id=data.model_id,
        )

        filename = data.topic.replace(" ", "_")[:40] + "_news.mp3"
        return StreamingResponse(
            audio_stream,
            media_type="audio/mpeg",
            headers={
                "Content-Disposition": f'attachment; filename="{filename}"',
                "X-Topic": data.topic,
                "X-Article-Count": str(len(articles)),
            },
        )
    except ValueError as ve:
        raise HTTPException(status_code=422, detail=str(ve))
    except Exception as e:
        logger.error("POST /audio/news TTS error: %s", e)
        raise HTTPException(status_code=500, detail=f"TTS generation failed: {e}")


# ── Telegram ────────────────────────────────────────────────────

@router.get(
    "/telegram/status/{token}",
    response_model=TelegramStatusResponse,
    tags=["Telegram"],
    summary="Check if a user token has a linked Telegram account",
)
async def telegram_status(token: str):
    """
    Returns whether the given user_token has been linked to a Telegram
    account via the bot's /start command.
    """
    conn = get_connection(token)
    if conn is None:
        return TelegramStatusResponse(connected=False)
    return TelegramStatusResponse(
        connected=True,
        username=conn.get("username"),
        first_name=conn.get("first_name"),
    )


@router.post(
    "/telegram/send-audio",
    tags=["Telegram"],
    summary="Send an audio file to a connected Telegram user",
)
async def telegram_send_audio(
    audio: UploadFile = File(..., description="MP3 audio file"),
    user_token: str = Form(..., description="User token linked via /start"),
    topic: str = Form(default="News Briefing", description="Topic for the caption"),
):
    """
    Sends the uploaded audio file to the Telegram user linked to `user_token`.
    The bot must have been connected via /start first.
    """
    try:
        audio_bytes = await audio.read()
        if not audio_bytes:
            raise HTTPException(status_code=422, detail="Empty audio file.")

        filename = audio.filename or f"{topic.replace(' ', '_')[:40]}_news.mp3"
        caption = f"🎙 Your audio briefing: {topic}"

        result = send_audio_to_user(
            token=user_token,
            audio_bytes=audio_bytes,
            filename=filename,
            caption=caption,
        )
        return result

    except ValueError as ve:
        raise HTTPException(status_code=422, detail=str(ve))
    except Exception as e:
        logger.error("POST /telegram/send-audio error: %s", e)
        raise HTTPException(status_code=500, detail=f"Failed to send audio: {e}")